name: PHP

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  run:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - php: 8.0
            composer: '--prefer-lowest'
            desc: "Lowest versions"
          - php: 8.0
            coverage: '--coverage-clover /tmp/clover.xml'
          - php: 8.1
    name: PHP ${{ matrix.php }} ${{ matrix.desc }}

    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 10

    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: ${{ matrix.php }}
        coverage: xdebug

    - name: Validate composer.json and composer.lock
      run: composer validate

    - name: Install dependencies
      run: composer update --prefer-dist --no-progress --no-suggest ${{ matrix.composer }}

    - name: Run PHPUnit
      run: vendor/bin/phpunit ${{ matrix.coverage }}

    - name: Upload coverage to Scrutinizer
      if: ${{ matrix.coverage }}
      uses: sudo-bot/action-scrutinizer@latest
      with:
        cli-args: "--format=php-clover /tmp/clover.xml"
